### ISSUE TITLE
Fails to link with default-features=false on Linux

### ISSUE THREAD

**Issue by RazrFalcon** [servo/rust-harfbuzz#177]
```toml
[dependencies]
harfbuzz = { version = "0.3.1", default-features = false }
```

All harfbuzz functions are marked as *undefined reference*.
